routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
use \Illuminate\Support\Facades\DB;

Auth::routes();
Route::get('check_email','ResetPasswodCtrl@check_email')->name('check_email');
Route::post('password_update/{id}','ResetPasswodCtrl@password_update')->name('password_update');

Route::middleware(['auth'])->group(function () {
    Route::get('/',function (){
        if(auth()->user()->hasRole('admin')){
            return view('backend.pages.index');
        }
        return view('backend.pages.userDashboard');
    });
    Route::get('/home',function (){
        if(auth()->user()->hasRole('admin')){
            return view('backend.pages.index');
        }
        return view('backend.pages.userDashboard');
    })->name('home');
    //Route::get('/home', 'HomeController@index')->name('home');

    //Routes of Admin and Backend
    Route::namespace('backend')->middleware(['role:admin'])->prefix('admin')->group(function () {

        // Routes of Clients:
        Route::prefix('clients')->group(function (){
            Route::get('all','clientsCtrl@index')->name('admin_clients_all');
            Route::get('create','clientsCtrl@create')->name('admin_clients_create');
            Route::post('store','clientsCtrl@store')->name('admin_clients_store');
            Route::get('show/{slug}','clientsCtrl@show')->name('admin_clients_show');
            Route::get('edit/{slug}','clientsCtrl@edit')->name('admin_clients_edit');
            Route::post('update/{slug}','clientsCtrl@update')->name('admin_clients_update');
            Route::post('destroy/{slug}','clientsCtrl@destroy')->name('admin_clients_destroy');
        });
        // Routes of users:
        Route::prefix('users')->group(function (){
            Route::get('all','usersCtrl@index')->name('admin_users_all');
            Route::get('create','usersCtrl@create')->name('admin_users_create');
            Route::post('store','usersCtrl@store')->name('admin_users_store');
            Route::get('show/{slug}','usersCtrl@show')->name('admin_users_show');
            Route::get('edit/{slug}','usersCtrl@edit')->name('admin_users_edit');
            Route::post('update/{slug}','usersCtrl@update')->name('admin_users_update');
            Route::post('destroy/{slug}','usersCtrl@destroy')->name('admin_users_destroy');
        });
        // Routes of products:
        Route::prefix('products')->group(function (){
            Route::get('all','productsCtrl@index')->name('admin_products_all');
            Route::get('create','productsCtrl@create')->name('admin_products_create');
            Route::post('store','productsCtrl@store')->name('admin_products_store');
            Route::get('show/{slug}','productsCtrl@show')->name('admin_products_show');
            Route::get('edit/{slug}','productsCtrl@edit')->name('admin_products_edit');
            Route::post('update/{slug}','productsCtrl@update')->name('admin_products_update');
            Route::post('destroy/{slug}','productsCtrl@destroy')->name('admin_products_destroy');
        });
        // Routes of categories:
        Route::prefix('categories')->group(function (){
            Route::get('all','categoryCtrl@index')->name('admin_categories_all');
            Route::get('create','categoryCtrl@create')->name('admin_categories_create');
            Route::post('store','categoryCtrl@store')->name('admin_categories_store');
            Route::get('show/{slug}','categoryCtrl@show')->name('admin_categories_show');
            Route::post('update/{slug}','categoryCtrl@update')->name('admin_categories_update');
            Route::post('destroy/{slug}','categoryCtrl@destroy')->name('admin_categories_destroy');
        });
        // Routes of itineraries:
        Route::prefix('itineraries')->group(function (){
            Route::get('all','itinerariesCtrl@index')->name('admin_itineraries_all');
            Route::get('show/{slug}','itinerariesCtrl@show')->name('admin_itineraries_show');
        });
        // Routes of reports:
        Route::prefix('reports')->group(function (){
            Route::get('create','reportsCtrl@create')->name('user_report_create');
            Route::post('user_day_report','reportsCtrl@user_day_report')->name('user_day_report');
            Route::post('client_report','reportsCtrl@client_report')->name('client_report');
        });


    });

    Route::post('filter','HomeController@filter')->name('filter')->middleware(['role:admin']);
    Route::get('reset_password',function (){
        $user = auth()->user();
        return view('auth.passwords.reset',compact('user'));
    })->name('reset_password');


    Route::namespace('backend')->middleware(['role:user'])->prefix('user')->group(function () {
        Route::post('start_new_line','itinerariesCtrl@start')->name('start_new_line');
        Route::post('end_line/{id}','itinerariesCtrl@end')->name('end_line');
        Route::get('create_order/{slug}','orderCtrl@create')->name('create_order');
        Route::post('store_order/{slug}','orderCtrl@store')->name('store_order');
        Route::get('user_itineraries_all','itinerariesCtrl@allOfUser')->name('user_itineraries_all');
        Route::get('user_products_all','productsCtrl@user_products_all')->name('user_products_all');
        Route::get('user_itineraries_show/{slug}','itinerariesCtrl@itemOfUser')->name('user_itineraries_show');
    });
});

app/Itinerary.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Itinerary extends Model
{
    use SoftDeletes;
    use HasSlug;


    /**
     * @var array
     */
    protected $guarded = ['id'];
    /**
     * @var array
     */
    protected $casts= [
        'start_location'=>'array',
        'end_location'=>'array',
    ];
    protected $dates= [
        'start','end','created_at','updated_at'
    ];
    /**
     * @var mixed
     */

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('start')
            ->saveSlugsTo('slug');
    }

    /**
     * @return string
     */

    public function getRouteKeyName() :string
    {
        return 'slug';
    }

    public function getCreatedFormatAttribute()
    {
        $time = $this->created_at?\Carbon\Carbon::parse($this->created_at)->format('Y-m-d H:i'): null;
        return $time;
    }
    public function getEndFormatAttribute()
    {
        $time = $this->end?\Carbon\Carbon::parse($this->end)->format('Y-m-d H:i'): null;
        return $time;
    }

    public function getEndedAttribute()
    {
        return ($this->end != null)? true: false;
    }
    public function getStatusAttribute()
    {
        if(!$this->end ){
            return 'حالي';
        }else{
            return 'منتهي في: '.$this->end_format;
        }
    }
    /**
     * @param $query
     * @return mixed
     */
    public function scopeCurrent($query)
    {
        return $query->whereNull('end')->whereNull('end_location');
    }
    public function scopeEnded($query)
    {
        return $query->whereNotNull('end')->whereNotNull('end_location');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Order::class, 'itinerary_id');
    }
    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
class Order extends Model
{
    use SoftDeletes;
    use HasSlug;


    /**
     * @var array
     */
    protected $guarded = ['id'];
    /**
     * @var array
     */
    protected $casts= [
        'location'=>'array',
        'data'=>'array',
    ];

    public function getTextTypeAttribute()
    {
        if((integer)$this->data['type'] == 1 ){
            return 'تسليم منتج';
        }elseif((integer)$this->data['type'] == 2){
            return ' استلام نقدية';
        }else{
            return ' عملية لغرض آخر';
        }
    }

    /**
     * @return SlugOptions
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('created_at')
            ->saveSlugsTo('slug');
    }

    /**
     * @return string
     */
    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class,'client_id');
    }
}

resources/views/backend/pages/itineraries/show.blade.php
@extends('backend.app')
@section('title') خط سير | {{$item->created_format}} @stop
@section('content')
    <!-- Page Content -->
    <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">خطوط السير</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url('/')}}">لوحة التحكم</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin_itineraries_all')}}">خطوط السير</a></li>
                        <li class="breadcrumb-item active">خط سير للمندوب : {{$item->user->name}} بتاريخ:
                        {{$item->created_at->format('Y/m/d')}}</li>
                    </ul>
                </div>

            </div>
        </div>
        <!-- /Page Header -->
        <div class="row justify-content-center">
            <div class="col-md-4 table-responsive">
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                         <i class="fa fa-clock-o h2"></i>
                        <br>
                        نقطة البداية
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>الوقت:</td>
                                <td>{{$item->created_format}}</td>
                            </tr>
                            <tr>
                                <td>الموقع:</td>
                                <td><a href=" https://maps.google.com/maps?q=loc:{{$item->start_location['lat'].','.$item->start_location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                            </tr>

                            <tr>
                                <td>مجموع المسافات التي قطعها:</td>
                                <td>{{$distance}} كيلو متر </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($item->orders()->count())
            <div class="row justify-content-center">
            @foreach($item->orders as $key=>$order)
                <div class="col-md-8 table-responsive">
                    <div class="card">
                        <div class="card-header bg-primary text-white text-center">
                            <i class="fa fa-truck h2"></i>
                            <br>
                            طلب رقم ({{$key+1}})
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table">
                                <tr class="text-center">
                                    <th style="min-width:150px">الوقت</th>
                                    <th style="min-width:150px">العميل</th>
                                    <th style="min-width:150px">موقع العملية</th>
                                    <th style="min-width:150px">موقع العميل</th>
                                    <th style="min-width:150px"> حالة الوصول</th>
                                </tr>
                                <tr class="text-center">
                                    <td>{{$order->created_format}}</td>
                                    <td>{{$order->client->name}}</td>
                                    <td><a href=" https://maps.google.com/maps?q=loc:{{$order->location['lat'].','.$order->location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                                    <td><a href=" https://maps.google.com/maps?q=loc:{{$order->client->location['lat'].','.$order->client->location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                                    <td> <span  class=" {{getAllowFarIndex(getTomTomDistatnce([0=>$order->location , 1=> $order->client->location ],true))['class']}}"> <p class="m-2">{{getAllowFarIndex(getTomTomDistatnce([0=>$order->location , 1=> $order->client->location ],true))['text']}}</p></span> </td>
                                </tr>
                            </table>
                            <table class="table mt-3">
                                <thead class="bg-primary text-white text-center">
                                <tr>
                                    <th colspan="3">
                                        تفاصيل العملية
                                    </th>
                                </tr>
                                </thead>
                                <tr>
                                    <th  style="min-width:150px">غرض العملية:</th><td colspan="2" >{{$order->text_type}}</td>
                                </tr>
                                @if((integer)$order->data['type'] == 1)
                                    <tr class=" text-center" style="background-color: #d0d3d4">
                                        <th>اسم المنتج</th>
                                        <th>الكمية</th>
                                        <th>إجمالي</th>
                                    </tr>
                                    <?php $proSum = 0 ;?>
                                    @foreach($order->data['products_ids'] as $key => $pro)
                                        <tr class="text-center">
                                            <td style="min-width:150px" >{{getItemById('products',$pro)->name}}</td>
                                            <td>{{$order->data['products_qty'][$key]}}  </td>
                                            <td>{{$order->data['products_qty'][$key] * getItemById('products',$pro)->cost}} ج.م </td>
                                        </tr>
                                        <?php  $proSum += $order->data['products_qty'][$key] * \DB::table('products')->where('id',$pro)->first()->cost ; ?>
                                    @endforeach
                                    <tr class="text-center">
                                        <th colspan="2">المجموع</th>
                                        <th>{{$proSum}} ج.م </th>
                                    </tr>
                                @elseif((integer)$order->data['type'] == 2)
                                    <tr class=" text-center" style="background-color: #d0d3d4">
                                        <th colspan="2"> البيان</th>
                                        <th>المبلغ</th>
                                    </tr>
                                    <?php $sum=0;?>
                                    @foreach($order->data['received_notice'] as $key => $notice)
                                        <tr class="text-center">
                                            <td style="min-width:150px" colspan="2">{{$notice}}</td> <td>{{$order->data['received_money'][$key]}} ج.م </td>
                                        </tr>
                                        <?php $sum+=$order->data['received_money'][$key] ?>
                                    @endforeach
                                    <tr class="text-center">
                                        <th colspan="2">المجموع</th>
                                        <th>{{$sum}} ج.م </th>
                                    </tr>

                                @endif
                                <tr class=" text-center" style="background-color: #dde2e2">
                                    <th colspan="3">ملاحظات</th>
                                </tr>
                                <tr class="text-center">
                                    <td style="min-width:150px" colspan="3" >{{$order->data['notes']??'لا يوجد'}}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            @endforeach
            </div>
        @endif
        <div class="row justify-content-center">
            @if($item->ended)
            <div class="col-md-4 table-responsive">
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                         <i class="fa fa-clock-o h2"></i>
                        <br>
                        نقطة النهاية
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>الوقت:</td>
                                <td>{{$item->end_format}}</td>
                            </tr>
                            <tr>
                                <td>الموقع:</td>
                                <td><a href=" https://maps.google.com/maps?q=loc:{{$item->end_location['lat'].','.$item->end_location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                            </tr>
                            <tr>
                                <td>البعد عن نقطة البدء:</td>
                                <td>{{getTomTomDistatnce([0=>$item->start_location,1=>$item->end_location ],true)}} كيلو متر</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            @else
            <div class="col-md-3 table-responsive">
                <div class="card">

                    <div class="card-body">
                        <div class="text-center">
                            الخط مازال مستمراً..
                        </div>
                    </div>
                </div>
            </div>
            @endif
        </div>
    </div>


@stop

resources/views/backend/pages/itineraries/user_show.blade.php
@extends('backend.app')
@section('title') خط سير | {{$item->created_format}} @stop
@section('content')
    <!-- Page Content -->
    <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">خطوط السير الخاصة بي</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url('/')}}">لوحة التحكم</a></li>
                        <li class="breadcrumb-item"><a href="{{route('user_itineraries_all')}}">خطوط السير</a></li>
                        <li class="breadcrumb-item active">خط سير بتاريخ:
                        {{$item->created_at->format('Y/m/d')}}</li>
                    </ul>
                </div>

            </div>
        </div>
        <!-- /Page Header -->
        <div class="row justify-content-center">
            <div class="col-md-4 table-responsive">
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                         <i class="fa fa-clock-o h2"></i>
                        <br>
                        نقطة البداية
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>الوقت:</td>
                                <td>{{$item->start->format('Y/m/d H:m')}}</td>
                            </tr>
                            <tr>
                                <td>الموقع:</td>
                                <td><a href=" https://maps.google.com/maps?q=loc:{{$item->start_location['lat'].','.$item->start_location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($item->orders()->count())
            <div class="row justify-content-center">
            @foreach($item->orders as $key=>$order)
                <div class="col-md-8 table-responsive">
                    <div class="card">
                        <div class="card-header bg-primary text-white text-center">
                            <i class="fa fa-truck h2"></i>
                            <br>
                            طلب رقم ({{$key+1}})
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table">
                                <tr class="text-center">
                                    <th style="min-width:150px">الوقت</th>
                                    <th style="min-width:150px">العميل</th>
                                    <th style="min-width:150px">موقع العملية</th>
                                    <th style="min-width:150px">موقع العميل</th>
                                </tr>
                                <tr class="text-center">
                                    <td>{{$order->created_at->format('Y/m/d H:m')}}</td>
                                    <td>{{$order->client->name}}</td>
                                    <td><a href=" https://maps.google.com/maps?q=loc:{{$order->location['lat'].','.$order->location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                                    <td><a href=" https://maps.google.com/maps?q=loc:{{$order->client->location['lat'].','.$order->client->location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                                </tr>
                            </table>
                            <table class="table mt-3">
                                <thead class="bg-primary text-white text-center">
                                <tr>
                                    <th colspan="3">
                                        تفاصيل العملية
                                    </th>
                                </tr>
                                </thead>
                                <tr>
                                    <th  style="min-width:150px">غرض العملية:</th><td colspan="2" >{{$order->text_type}}</td>
                                </tr>
                                @if((integer)$order->data['type'] == 1)
                                    <tr class=" text-center" style="background-color: #d0d3d4">
                                        <th>اسم المنتج</th>
                                        <th>الكمية</th>
                                        <th>إجمالي</th>
                                    </tr>
                                <?php $proSum = 0 ;?>
                                @foreach($order->data['products_ids'] as $key => $pro)
                                <tr class="text-center">
                                    <td style="min-width:150px" >{{getItemById('products',$pro)->name}}</td>
                                    <td>{{$order->data['products_qty'][$key]}}  </td>
                                    <td>{{$order->data['products_qty'][$key] * getItemById('products',$pro)->cost}} ج.م </td>
                                </tr>
                                    <?php  $proSum += $order->data['products_qty'][$key] * \DB::table('products')->where('id',$pro)->first()->cost ; ?>
                                @endforeach
                                    <tr class="text-center">
                                        <th colspan="2">المجموع</th>
                                        <th>{{$proSum}} ج.م </th>
                                    </tr>
                                @elseif((integer)$order->data['type'] == 2)
                                    <tr class=" text-center" style="background-color: #d0d3d4">
                                        <th colspan="2"> البيان</th>
                                        <th>المبلغ</th>
                                    </tr>
                                <?php $sum=0;?>
                                    @foreach($order->data['received_notice'] as $key => $notice)
                                        <tr class="text-center">
                                            <td style="min-width:150px" colspan="2">{{$notice}}</td> <td>{{$order->data['received_money'][$key]}} ج.م </td>
                                        </tr>
                                        <?php $sum+=$order->data['received_money'][$key] ?>
                                    @endforeach
                                    <tr class="text-center">
                                        <th colspan="2">المجموع</th>
                                        <th>{{$sum}} ج.م </th>
                                    </tr>

                                @endif
                                <tr class=" text-center" style="background-color: #dde2e2">
                                    <th colspan="3">ملاحظات</th>
                                </tr>
                                <tr class="text-center">
                                    <td style="min-width:150px" colspan="3" >{{$order->data['notes']??'لا يوجد'}}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            @endforeach
            </div>
        @endif
        <div class="row justify-content-center">
            @if($item->ended)
            <div class="col-md-4 table-responsive">
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                         <i class="fa fa-clock-o h2"></i>
                        <br>
                        نقطة النهاية
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>الوقت:</td>
                                <td>{{$item->end->format('Y/m/d H:m')}}</td>
                            </tr>
                            <tr>
                                <td>الموقع:</td>
                                <td><a href=" https://maps.google.com/maps?q=loc:{{$item->end_location['lat'].','.$item->end_location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                            </tr>

                        </table>
                    </div>
                </div>
            </div>
            @else
            <div class="col-md-3 table-responsive">
                <div class="card">

                    <div class="card-body">
                        <div class="text-center">
                            الخط مازال مستمراً..
                        </div>
                    </div>
                </div>
            </div>
            @endif
        </div>
    </div>


@stop