routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;
use \Illuminate\Support\Facades\DB;

Auth::routes();
Route::get('check_email','ResetPasswodCtrl@check_email')->name('check_email');
Route::post('password_update/{id}','ResetPasswodCtrl@password_update')->name('password_update');

Route::middleware(['auth'])->group(function () {
    Route::get('/',function (){
        if(auth()->user()->hasRole('admin')){
            return view('backend.pages.index');
        }
        return view('backend.pages.userDashboard');
    });
    Route::get('/home',function (){
        if(auth()->user()->hasRole('admin')){
            return view('backend.pages.index');
        }
        return view('backend.pages.userDashboard');
    })->name('home');
    //Route::get('/home', 'HomeController@index')->name('home');

    //Routes of Admin and Backend
    Route::namespace('backend')->middleware(['role:admin'])->prefix('admin')->group(function () {

        // Routes of Clients:
        Route::prefix('clients')->group(function (){
            Route::get('all','clientsCtrl@index')->name('admin_clients_all');
            Route::get('create','clientsCtrl@create')->name('admin_clients_create');
            Route::post('store','clientsCtrl@store')->name('admin_clients_store');
            Route::get('show/{slug}','clientsCtrl@show')->name('admin_clients_show');
            Route::get('edit/{slug}','clientsCtrl@edit')->name('admin_clients_edit');
            Route::post('update/{slug}','clientsCtrl@update')->name('admin_clients_update');
            Route::post('destroy/{slug}','clientsCtrl@destroy')->name('admin_clients_destroy');
        });
        // Routes of users:
        Route::prefix('users')->group(function (){
            Route::get('all','usersCtrl@index')->name('admin_users_all');
            Route::get('create','usersCtrl@create')->name('admin_users_create');
            Route::post('store','usersCtrl@store')->name('admin_users_store');
            Route::get('show/{slug}','usersCtrl@show')->name('admin_users_show');
            Route::get('edit/{slug}','usersCtrl@edit')->name('admin_users_edit');
            Route::post('update/{slug}','usersCtrl@update')->name('admin_users_update');
            Route::post('destroy/{slug}','usersCtrl@destroy')->name('admin_users_destroy');
        });
        // Routes of products:
        Route::prefix('products')->group(function (){
            Route::get('all','productsCtrl@index')->name('admin_products_all');
            Route::get('create','productsCtrl@create')->name('admin_products_create');
            Route::post('store','productsCtrl@store')->name('admin_products_store');
            Route::get('show/{slug}','productsCtrl@show')->name('admin_products_show');
            Route::get('edit/{slug}','productsCtrl@edit')->name('admin_products_edit');
            Route::post('update/{slug}','productsCtrl@update')->name('admin_products_update');
            Route::post('destroy/{slug}','productsCtrl@destroy')->name('admin_products_destroy');
        });
        // Routes of categories:
        Route::prefix('categories')->group(function (){
            Route::get('all','categoryCtrl@index')->name('admin_categories_all');
            Route::get('create','categoryCtrl@create')->name('admin_categories_create');
            Route::post('store','categoryCtrl@store')->name('admin_categories_store');
            Route::get('show/{slug}','categoryCtrl@show')->name('admin_categories_show');
            Route::post('update/{slug}','categoryCtrl@update')->name('admin_categories_update');
            Route::post('destroy/{slug}','categoryCtrl@destroy')->name('admin_categories_destroy');
        });
        // Routes of itineraries:
        Route::prefix('itineraries')->group(function (){
            Route::get('all','itinerariesCtrl@index')->name('admin_itineraries_all');
            Route::get('show/{slug}','itinerariesCtrl@show')->name('admin_itineraries_show');
        });
        // Routes of reports:
        Route::prefix('reports')->group(function (){
            Route::get('create','reportsCtrl@create')->name('user_report_create');
            Route::post('user_day_report','reportsCtrl@user_day_report')->name('user_day_report');
            Route::post('client_report','reportsCtrl@client_report')->name('client_report');
        });


    });

    Route::post('filter','HomeController@filter')->name('filter')->middleware(['role:admin']);
    Route::get('reset_password',function (){
        $user = auth()->user();
        return view('auth.passwords.reset',compact('user'));
    })->name('reset_password');


    Route::namespace('backend')->middleware(['role:user'])->prefix('user')->group(function () {
        Route::post('start_new_line','itinerariesCtrl@start')->name('start_new_line');
        Route::post('end_line/{id}','itinerariesCtrl@end')->name('end_line');
        Route::get('create_order/{slug}','orderCtrl@create')->name('create_order');
        Route::post('store_order/{slug}','orderCtrl@store')->name('store_order');
        Route::get('user_itineraries_all','itinerariesCtrl@allOfUser')->name('user_itineraries_all');
        Route::get('user_products_all','productsCtrl@user_products_all')->name('user_products_all');
        Route::get('user_itineraries_show/{slug}','itinerariesCtrl@itemOfUser')->name('user_itineraries_show');
    });
});

app/Itinerary.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Itinerary extends Model
{
    use SoftDeletes;
    use HasSlug;


    /**
     * @var array
     */
    protected $guarded = ['id'];
    /**
     * @var array
     */
    protected $casts= [
        'start_location'=>'array',
        'end_location'=>'array',
    ];
    protected $dates= [
        'start','end','created_at','updated_at'
    ];
    /**
     * @var mixed
     */

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('start')
            ->saveSlugsTo('slug');
    }

    /**
     * @return string
     */

    public function getRouteKeyName() :string
    {
        return 'slug';
    }

    public function getCreatedFormatAttribute()
    {
        $time = $this->created_at?\Carbon\Carbon::parse($this->created_at)->format('Y-m-d H:i'): null;
        return $time;
    }
    public function getEndFormatAttribute()
    {
        $time = $this->end?\Carbon\Carbon::parse($this->end)->format('Y-m-d H:i'): null;
        return $time;
    }

    public function getEndedAttribute()
    {
        return ($this->end != null)? true: false;
    }
    public function getStatusAttribute()
    {
        if(!$this->end ){
            return 'حالي';
        }else{
            return 'منتهي في: '.$this->end_format;
        }
    }
    /**
     * @param $query
     * @return mixed
     */
    public function scopeCurrent($query)
    {
        return $query->whereNull('end')->whereNull('end_location');
    }
    public function scopeEnded($query)
    {
        return $query->whereNotNull('end')->whereNotNull('end_location');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Order::class, 'itinerary_id');
    }
    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
class Order extends Model
{
    use SoftDeletes;
    use HasSlug;


    /**
     * @var array
     */
    protected $guarded = ['id'];
    /**
     * @var array
     */
    protected $casts= [
        'location'=>'array',
        'data'=>'array',
    ];

    public function getTextTypeAttribute()
    {
        if((integer)$this->data['type'] == 1 ){
            return 'تسليم منتج';
        }elseif((integer)$this->data['type'] == 2){
            return ' استلام نقدية';
        }else{
            return ' عملية لغرض آخر';
        }
    }

    /**
     * @return SlugOptions
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('created_at')
            ->saveSlugsTo('slug');
    }

    /**
     * @return string
     */
    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class,'client_id');
    }
}

resources/views/backend/pages/reports/create.blade.php
@extends('backend.app')
@section('title') إنشاء التقارير  @stop
@push('cssFiles')
    <link rel="stylesheet" type="text/css" href="{{asset('backend/assets/css/dataTables.bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('backend/assets/css/select2.min.css')}}">
@endpush


@section('content')

    <!-- Page Content -->
    <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">إنشاء التقارير</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url('/')}}">لوحة التحكم</a></li>
                        <li class="breadcrumb-item active">إنشاء التقارير</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <div class="row">
            <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6">
                <div class="card dash-widget">
                    <div class="card-body">
                        <span class="dash-widget-icon"><i class="fa fa-user"></i></span>
                        <div class="dash-widget-info">
                            <span class="text-lg">إنشاء تقرير بالفترة عن أحد المندوبين </span>
                        </div>
                        <br  class="my-3">
                        <div>
                            <form action="{{route('user_day_report')}}" class="mt-3" method="POST">@csrf
                                <div class="form-group">
                                    <lable>اختر المندوب</lable>
                                    <select name="user_id" class="form-control"  required>
                                        <option value="">اختر..</option>
                                        @foreach(\App\User::role('user')->select('id','name')->get() as $key=>$user)
                                            <option value="{{$user->id}}" @if (old('user_id') == $user->id) selected @endif>{{$user->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <lable>حدد تاريخ بدء الفترة</lable>
                                    <input type="date" name="from" class="form-control @error('from') is-invalid @enderror" value="{{old('from')}}" required>
                                    @error('from')
                                    <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <lable>حدد تاريخ انتهاء الفترة</lable>
                                    <input type="date" name="to" class="form-control @error('to') is-invalid @enderror" value="{{old('to')}}" required>
                                    @error('to')
                                    <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group text-center">
                                    <input type="submit" value="إنشاء تقرير" class="btn btn-outline-dark form-control">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6">
                <div class="card dash-widget">
                    <div class="card-body">
                        <span class="dash-widget-icon"><i class="fa fa-users"></i></span>
                        <div class="dash-widget-info">
                            <span class="text-lg">إنشاء تقرير بالفترة عن أحد العملاء </span>
                        </div>

                        <br  class="my-3">
                        <div>
                            <form action="{{route('client_report')}}" class="mt-3" method="POST">@csrf
                                <div class="form-group">
                                    <lable>اختر العميل</lable>
                                    <select name="client_id" class="form-control" required>
                                        <option value="">اختر..</option>
                                        @foreach(\App\Client::select('id','name')->get() as $key=>$user)
                                            <option value="{{$user->id}}" @if(old('client_id') == $user->id) selected @endif>{{$user->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <lable>حدد تاريخ بدء الفترة</lable>
                                    <input type="date" name="from2" class="form-control @error('from2') is-invalid @enderror" value="{{old('from2')}}" required>
                                    @error('from2')
                                    <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <lable>حدد تاريخ انتهاء الفترة</lable>
                                    <input type="date" name="to2" class="form-control @error('to2') is-invalid @enderror" value="{{old('to2')}}" required>
                                    @error('to2')
                                    <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group text-center">
                                    <input type="submit" value="إنشاء تقرير" class="btn btn-outline-dark form-control ">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /Page Content -->


@stop
@push('footerScripts')
    <script src="{{asset('backend/assets/js/select2.min.js')}}"></script>
@endpush

resources/views/backend/pages/reports/index.blade.php
@extends('backend.app')
@section('title') التقارير  @stop
@push('cssFiles')
    <link rel="stylesheet" type="text/css" href="{{asset('backend/assets/css/dataTables.bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('backend/assets/css/select2.min.css')}}">
@endpush


@section('content')

    <!-- Page Content -->
    <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">التقارير</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{url('/')}}">لوحة التحكم</a></li>
                        @if(url()->current() == route('user_day_report'))
                        <li class="breadcrumb-item active">تقرير عن أحد المندوبين في فترة محددة</li>
                        @elseif (url()->current() == route('client_report'))
                        <li class="breadcrumb-item active">تقرير عن أحد العملاء في فترة محددة</li>
                        @endif

                    </ul>
                </div>
            </div>
        </div>
        <!-- /Page Header -->

        @if(url()->current() == route('user_day_report'))
            <div class="row ">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header bg-primary text-center">
                            <span>
                             البيانات الأساسية للتقرير
                            </span>
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table">
                                <tr><th>المندوب:</th> <td>{{$user->name}}</td></tr>
                                <tr><th>تاريخ البدء:</th> <td>{{\Carbon\Carbon::create($from)->format('Y/m/d')}}</td></tr>
                                <tr><th>تاريخ الانتهاء:</th> <td>{{\Carbon\Carbon::create($to)->format('Y/m/d')}}</td></tr>
                                <tr><th>عدد خطوط السير في هذه الفترة:</th> <td>{{count($data)?count($data):0}}</td></tr>
                                <tr><th>إجمالي المسافات التي قطعها في هذه الفترة:</th> <td>{{$distance}} كيلو متر </td></tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 mt-3">
                    <div class="card">
                        <div class="card-header bg-primary text-center">
                            <span>
                            خطوط السير التي قام بها
                            </span>
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table">
                                <th class="sorting" tabindex="0"
                                    aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                    aria-label="Client ID: activate to sort column ascending"
                                    style="min-width: 200px;">وقت البدء</th>
                                <th class="sorting" tabindex="0"
                                    aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                    aria-label="Mobile: activate to sort column ascending"
                                    style="min-width: 200px;">الحالة</th>
                                <th class="sorting" tabindex="0"
                                    aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                    aria-label="Status: activate to sort column ascending"
                                    style="min-width: 150px;">عدد الطلبات</th>
                                <th class="sorting" tabindex="0"
                                    aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                    aria-label="Status: activate to sort column ascending"
                                    style="min-width: 150px;"> المسافة المقطوعة</th>
                                <th class="text-center sorting" tabindex="0"
                                    aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                    aria-label="Action: activate to sort column ascending"
                                    style="min-width: 100px;"></th>
                                </tr>
                                @foreach($data as $key=>$val)
                                <tr>
                                    <td>{{$val->start->format('Y-m-d h:i')}}</td>
                                    <td>{{$val->status}}</td>
                                    <td>{{$val->orders()->count()}}</td>
                                    <td>{{$val->distance? $val->distance.' كيلو متر ' :'لم يتم حفظ المسافة'}}</td>
                                    <td><a href="{{route('admin_itineraries_show',$val->slug)}}" class="btn btn-link"> عرض</a> </td>
                                </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-7">
                <div class="dataTables_paginate paging_simple_numbers"
                     id="DataTables_Table_0_paginate">
                    {{$data->onEachSide(1)->links()}}
                </div>
            </div>
            </div>
        @elseif (url()->current() == route('client_report'))
        <div class="row ">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-primary text-center">
                            <span>
                             البيانات الأساسية للتقرير
                            </span>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table">
                            <tr><th>العميل:</th> <td>{{$client->name}}</td></tr>
                            <tr><th>تاريخ البدء:</th> <td>{{\Carbon\Carbon::create($from)->format('Y/m/d')}}</td></tr>
                            <tr><th>تاريخ الانتهاء:</th> <td>{{\Carbon\Carbon::create($to)->format('Y/m/d')}}</td></tr>
                            <tr><th>عدد الطلبات التي تمت له:</th> <td>{{count($data)?count($data):0}}</td></tr>
                        </table>
                    </div>
                </div>
            </div>
            @foreach($data as $key => $order)
            <div class="col-md-12 mt-2">
                <div class="card">
                    <div class="card-header bg-dark text-center text-white">
                        <span style="font-size: 25px">
                            عملية رقم {{$key +1}}
                        </span>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table">
                            <tr class="text-center">
                                <th style="min-width:150px">المندوب</th>
                                <th style="min-width:150px">الوقت</th>
                                <th style="min-width:150px">العميل</th>
                                <th style="min-width:150px">موقع العملية</th>
                                <th style="min-width:150px">موقع العميل</th>
                                <th style="min-width:150px"> حالة الوصول</th>
                            </tr>
                            <tr class="text-center">
                                <td>{{$order->user->name}}</td>
                                <td>{{$order->created_at->format('Y-m-d h:i')}}</td>
                                <td>{{$order->client->name}}</td>
                                <td><a href=" https://maps.google.com/maps?q=loc:{{$order->location['lat'].','.$order->location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                                <td><a href=" https://maps.google.com/maps?q=loc:{{$order->client->location['lat'].','.$order->client->location['lng']}}" class="btn btn-link btn-sm" target="_blank"> عرض</a> </td>
                                <td> <span  class=" {{getAllowFarIndex(getTomTomDistatnce([0=>$order->location , 1=> $order->client->location ],true))['class']}}"> <p class="m-2">{{getAllowFarIndex(getTomTomDistatnce([0=>$order->location , 1=> $order->client->location ],true))['text']}}</p></span> </td>
                            </tr>
                        </table>
                        <table class="table mt-3">
                            <thead class="bg-primary text-white text-center">
                            <tr>
                                <th colspan="3">
                                    تفاصيل العملية
                                </th>
                            </tr>
                            </thead>
                            <tr>
                                <th  style="min-width:150px">غرض العملية:</th><td colspan="2" >{{$order->text_type}}</td>
                            </tr>
                            @if((integer)$order->data['type'] == 1)
                                <tr class=" text-center" style="background-color: #d0d3d4">
                                    <th colspan="2">اسم المنتج</th>
                                    <th>الكمية</th>
                                </tr>
                                @foreach($order->data['products_ids'] as $key => $pro)
                                    <tr class="text-center">
                                        <td style="min-width:150px" colspan="2">{{getItemById('products',$pro)->name}}</td>
                                        <td>{{$order->data['products_qty'][$key]}}  </td>
                                    </tr>
                                @endforeach

                            @elseif((integer)$order->data['type'] == 2)
                                <tr class=" text-center" style="background-color: #d0d3d4">
                                    <th colspan="2"> البيان</th>
                                    <th>المبلغ</th>
                                </tr>
                                @foreach($order->data['received_notice'] as $key => $notice)
                                    <tr class="text-center">
                                        <td style="min-width:150px" colspan="2">{{$notice}}</td> <td>{{$order->data['received_money'][$key]}} ج.م </td>
                                    </tr>
                                @endforeach

                            @endif
                            <tr class=" text-center" style="background-color: #dde2e2">
                                <th colspan="3">ملاحظات</th>
                            </tr>
                            <tr class="text-center">
                                <td style="min-width:150px" colspan="3" >{{$order->data['notes']??'لا يوجد'}}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            @endforeach
            <div class="col-sm-12 col-md-7">
                <div class="dataTables_paginate paging_simple_numbers"
                     id="DataTables_Table_0_paginate">
                    {{$data->onEachSide(1)->links()}}
                </div>
            </div>
        </div>
        @endif

    </div>
    <!-- /Page Content -->


@stop
@push('footerScripts')
    <script src="{{asset('backend/assets/js/select2.min.js')}}"></script>
@endpush